# L64 3D response-shaped line-of-sight curvature candidate. The assigned
# parent's envelope-aware joint-state oscillator and posterior lag remain the
# propulsive carrier. Target geometry requests a bounded yaw rate; only the
# desired-minus-observed response error biases posterior mean curvature.

function target_policy_params(; L::Int=64)
    return (
        version="dogfish_target_control_v20_los_yaw_response_curvature",
        L=Float64(L),
        drive_period=0.80,
        control_period=0.80,
        drive_amplitude=22.0 * pi / 180,
        drive_mu=0.35,
        drive_tail_lag_gain=0.80,
        drive_tail_damping=0.65,
        target_scale_floor_L=0.25,
        vector_forward_floor=0.15,
        vector_angle_limit=1.25,
        route_bearing_weight=0.40,
        route_vector_weight=0.60,
        route_error_scale=0.40,
        desired_yaw_rate_limit=0.65,
        yaw_response_scale=0.65,
        yaw_rate_error_scale=0.35,
        turn_curvature_limit=10.0 * pi / 180,
        approach_distance_L=2.10,
        approach_min_yaw_gain=0.45,
        action_soft_limit=1750.0 * pi / 180,
        action_soft_limit_power=8.0,
    )
end

@inline function _safe(value, fallback)
    parsed = Float64(value)
    return isfinite(parsed) ? parsed : fallback
end

@inline function _clamp01(value)
    return clamp(value, 0.0, 1.0)
end

@inline function _soft_limit(value, limit, power)
    safe_limit = max(_safe(limit, 1.0), 1.0e-6)
    safe_power = max(_safe(power, 2.0), 2.0)
    ratio = abs(_safe(value, 0.0)) / safe_limit
    return _safe(value, 0.0) / (1 + ratio^safe_power)^(1 / safe_power)
end

function guidance_module(state, params)
    distance_L = max(_safe(state.distance_L, 1.0), 1.0e-6)
    scale_L = max(distance_L, params.target_scale_floor_L)

    # The target vector is L-normalized and already expressed in the body
    # frame. The fish swims along negative body x, so positive target y calls
    # for negative world yaw. Bearing and vector angle retain independent
    # geometry paths but are combined into one route-scale request.
    target_x_L = _safe(state.target_body_L[1], -distance_L)
    target_y_L = _safe(state.target_body_L[2], 0.0)
    forward_component = -target_x_L / scale_L
    lateral_component = target_y_L / scale_L
    vector_angle = atan(
        lateral_component,
        max(forward_component, params.vector_forward_floor),
    )
    vector_angle = clamp(
        vector_angle,
        -params.vector_angle_limit,
        params.vector_angle_limit,
    )
    bearing = clamp(
        _safe(state.bearing, 0.0),
        -params.vector_angle_limit,
        params.vector_angle_limit,
    )
    route_error =
        params.route_bearing_weight * bearing +
        params.route_vector_weight * vector_angle

    # Reduce route-scale yaw only inside the terminal band. No candidate in the
    # inherited population reached it, so far-field steering remains unchanged.
    approach = _clamp01(distance_L / max(params.approach_distance_L, 1.0e-6))
    yaw_gain =
        params.approach_min_yaw_gain +
        (1 - params.approach_min_yaw_gain) * approach
    desired_yaw_rate =
        -params.desired_yaw_rate_limit * yaw_gain *
        tanh(route_error / max(params.route_error_scale, 1.0e-6))

    turn_rate = hasproperty(state, :turn_rate_recent) ?
        _safe(state.turn_rate_recent, 0.0) :
        _safe(state.heading_rate, 0.0)
    bounded_yaw_response =
        params.yaw_response_scale *
        tanh(turn_rate / max(params.yaw_response_scale, 1.0e-6))
    yaw_rate_error = desired_yaw_rate - bounded_yaw_response

    # Mean curvature is generated by response error, not by an inferred static
    # bend polarity alone. Correct-sign yaw releases the bend; excessive or
    # wrong-sign yaw reverses it through the same posterior channel.
    mean_tail_tangent =
        params.turn_curvature_limit *
        tanh(yaw_rate_error / max(params.yaw_rate_error_scale, 1.0e-6))
    return (
        mean_tail_tangent=mean_tail_tangent,
        route_error=route_error,
        bearing=bearing,
        vector_angle=vector_angle,
        desired_yaw_rate=desired_yaw_rate,
        turn_rate=turn_rate,
        bounded_yaw_response=bounded_yaw_response,
        yaw_rate_error=yaw_rate_error,
        distance_L=distance_L,
        yaw_gain=yaw_gain,
    )
end

function drive_module(state, guidance, params)
    omega = 2 * pi / params.drive_period
    amplitude = params.drive_amplitude
    q1 = _safe(state.phi[1], 0.0)
    q2 = _safe(state.phi[2], 0.0)
    qd1 = _safe(state.phi_dot[1], 0.0)
    qd2 = _safe(state.phi_dot[2], 0.0)

    # Joint state supplies phase; the posterior joint follows the anterior bend
    # with lag around the response-shaped mean tangent.
    vdp_drive = params.drive_mu * (1 - (q1 / amplitude)^2) * qd1
    head_accel = vdp_drive - omega^2 * q1
    tail_target =
        guidance.mean_tail_tangent - q1 -
        params.drive_tail_lag_gain * qd1 / max(omega, eps(omega))
    tail_accel =
        omega^2 * (tail_target - q2) -
        2 * params.drive_tail_damping * omega * qd2
    return (head_accel=head_accel, tail_accel=tail_accel)
end

function target_policy(state, params)
    guidance = guidance_module(state, params)
    drive = drive_module(state, guidance, params)
    return (
        phi_ddot=(
            _soft_limit(
                drive.head_accel,
                params.action_soft_limit,
                params.action_soft_limit_power,
            ),
            _soft_limit(
                drive.tail_accel,
                params.action_soft_limit,
                params.action_soft_limit_power,
            ),
        ),
    )
end
